name: Deploy on Google Cloud Platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud --quiet config set run/region ${{ secrets.REGION }}

          gcloud --quiet run deploy ${{ secrets.SERVICE_NAME }} \
            --source $(pwd) \
            --allow-unauthenticated \
            --platform managed

          gcloud --quiet run services update-traffic ${{ secrets.SERVICE_NAME }} --to-latest
